# Generated by Django 2.2 on 2019-10-05 11:13

from django.db import migrations, models
import index.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(default='', upload_to=index.models.get_upload_static_image)),
            ],
            options={
                'verbose_name_plural': 'Upload Image',
            },
        ),
    ]
