# Generated by Django 2.2 on 2019-10-05 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload_image',
            old_name='Image',
            new_name='image',
        ),
    ]
