# Generated by Django 2.2 on 2019-10-05 11:36

import django.core.validators
from django.db import migrations, models
import index.models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20191005_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amazing_Places',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to=index.models.get_amazing_places_image)),
                ('title', models.CharField(default='', max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('description', models.CharField(default='', max_length=500, validators=[django.core.validators.MinLengthValidator(3)])),
                ('link', models.CharField(default='', max_length=500, validators=[django.core.validators.URLValidator()])),
            ],
            options={
                'verbose_name_plural': 'Amazing Places',
            },
        ),
    ]
