# Generated by Django 2.2 on 2019-10-05 12:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_amazing_photos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shedule_Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=30, validators=[django.core.validators.MinLengthValidator(4)])),
                ('email', models.EmailField(max_length=254)),
                ('group_members', models.CharField(default='', max_length=2, validators=[django.core.validators.MinLengthValidator(1)])),
                ('message', models.CharField(default='', max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Shedule Ride',
            },
        ),
    ]
